#include <TexturePCH.h>

EZ_STATICLINK_LIBRARY(Texture)
{
  if (bReturn)
    return;

  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_BC);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_BC4BC5);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_BC6HBC7);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_BCDirectCompute);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexCompress);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexCompressGPU);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexConvert);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexD3D11);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexD3D12);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexDDS);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexFlipRotate);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexHDR);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexImage);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexMipmaps);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexMisc);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexNormalMaps);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexPMAlpha);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexResize);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexTGA);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexUtil);
  EZ_STATICLINK_REFERENCE(Texture_DirectXTex_DirectXTexWIC);
  EZ_STATICLINK_REFERENCE(Texture_Image_Conversions_DXTConversions);
  EZ_STATICLINK_REFERENCE(Texture_Image_Conversions_DXTexConversions);
  EZ_STATICLINK_REFERENCE(Texture_Image_Conversions_PixelConversions);
  EZ_STATICLINK_REFERENCE(Texture_Image_Conversions_SwizzleConversions);
  EZ_STATICLINK_REFERENCE(Texture_Image_Formats_BmpFileFormat);
  EZ_STATICLINK_REFERENCE(Texture_Image_Formats_DdsFileFormat);
  EZ_STATICLINK_REFERENCE(Texture_Image_Formats_StbImageFileFormats);
  EZ_STATICLINK_REFERENCE(Texture_Image_Formats_TgaFileFormat);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_Image);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageConversion);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageFileFormat);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageFilter);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageFormat);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageFormatMappings);
  EZ_STATICLINK_REFERENCE(Texture_Image_Implementation_ImageUtils);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_InputFiles);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_OutputFormat);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_Processor);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_TargetFormat);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_Texture2D);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_TextureCube);
  EZ_STATICLINK_REFERENCE(Texture_TexConv_Implementation_TextureModifications);
  EZ_STATICLINK_REFERENCE(Texture_Utils_Implementation_TextureGroupDesc);
  EZ_STATICLINK_REFERENCE(Texture_Utils_Implementation_TexturePacker);
  EZ_STATICLINK_REFERENCE(Texture_ezTexFormat_ezTexFormat);
}

