#include <PCH.h>

EZ_STATICLINK_LIBRARY(RendererCore)
{
  if (bReturn)
    return;

  EZ_STATICLINK_REFERENCE(RendererCore_Components_Implementation_CameraComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Components_Implementation_RenderComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Components_Implementation_SkyBoxComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Components_Implementation_SpriteComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Components_Implementation_SpriteRenderer);
  EZ_STATICLINK_REFERENCE(RendererCore_Debug_Implementation_DebugRenderer);
  EZ_STATICLINK_REFERENCE(RendererCore_Debug_Implementation_Inconsolata);
  EZ_STATICLINK_REFERENCE(RendererCore_Debug_Implementation_SimpleASCIIFont);
  EZ_STATICLINK_REFERENCE(RendererCore_GPUResourcePool_Implementation_GPUResourcePool);
  EZ_STATICLINK_REFERENCE(RendererCore_Lights_Implementation_AmbientLightComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Lights_Implementation_DirectionalLightComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Lights_Implementation_LightComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Lights_Implementation_PointLightComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Lights_Implementation_SpotLightComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Material_Implementation_MaterialResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Meshes_Implementation_MeshBufferResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Meshes_Implementation_MeshComponent);
  EZ_STATICLINK_REFERENCE(RendererCore_Meshes_Implementation_MeshRenderer);
  EZ_STATICLINK_REFERENCE(RendererCore_Meshes_Implementation_MeshResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Meshes_Implementation_MeshResourceDescriptor);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_DataProviders_ClusteredDataProvider);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_ExtractedRenderData);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Extractor);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_FrameDataProvider);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_AntialiasingPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_BloomPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_BlurPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_DepthOnlyPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_ForwardRenderPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_MsaaResolvePass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_MsaaUpscalePass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_ScreenSpaceAmbientOcclusion);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_SelectionHighlightPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_SeparatedBilateralBlur);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_SimpleRenderPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_SourcePass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_TargetPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_Passes_TonemapPass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_RenderData);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_RenderPipeline);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_RenderPipelinePass);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_RenderPipelineResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_RenderPipelineResourceLoader);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_SortingFunctions);
  EZ_STATICLINK_REFERENCE(RendererCore_Pipeline_Implementation_View);
  EZ_STATICLINK_REFERENCE(RendererCore_RenderContext_Implementation_RenderContext);
  EZ_STATICLINK_REFERENCE(RendererCore_RenderLoop_Implementation_RenderLoop);
  EZ_STATICLINK_REFERENCE(RendererCore_ShaderCompiler_Implementation_PermutationGenerator);
  EZ_STATICLINK_REFERENCE(RendererCore_ShaderCompiler_Implementation_ShaderCompiler);
  EZ_STATICLINK_REFERENCE(RendererCore_ShaderCompiler_Implementation_ShaderManager);
  EZ_STATICLINK_REFERENCE(RendererCore_ShaderCompiler_Implementation_ShaderParser);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ConstantBufferStorage);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_Helper);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ShaderPermutationBinary);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ShaderPermutationResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ShaderResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ShaderStageBinary);
  EZ_STATICLINK_REFERENCE(RendererCore_Shader_Implementation_ShaderStateDescriptor);
  EZ_STATICLINK_REFERENCE(RendererCore_Textures_Texture2DResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Textures_TextureCubeResource);
  EZ_STATICLINK_REFERENCE(RendererCore_Textures_TextureLoader);
  EZ_STATICLINK_REFERENCE(RendererCore_Textures_TextureUtils);
}



