set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG "Debug")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV "Dev")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE "Shipping")

set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG_UPPER "DEBUG")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV_UPPER "DEV")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE_UPPER "SHIPPING")

set_property(GLOBAL PROPERTY EZ_DEV_BUILD_LINKERFLAGS "DEBUG")

set_property(GLOBAL PROPERTY EZ_CMAKE_RELPATH "Code/BuildSystem/CMake")
set_property(GLOBAL PROPERTY EZ_CMAKE_RELPATH_CODE "Code")

set_property(GLOBAL PROPERTY EZ_CONFIG_PATH_7ZA "${CMAKE_SOURCE_DIR}/Data/Tools/Precompiled/7za.exe")

set_property(GLOBAL PROPERTY EZ_CONFIG_QT_WINX64_VERSION "Qt-5.13.0-vs141-x64")
set_property(GLOBAL PROPERTY EZ_CONFIG_QT_WINX64_URL "https://github.com/ezEngine/thirdparty/releases/download/Qt-5.13.0-vs141-x64/Qt-5.13.0-vs141-x64.zip")

