#include "StandardTypes.h"

// *********************************************
// ***** Standard POD Types for Properties *****

EZ_IMPLEMENT_REFLECTABLE_TYPE(bool);

EZ_IMPLEMENT_REFLECTABLE_TYPE(float);
EZ_IMPLEMENT_REFLECTABLE_TYPE(double);

EZ_IMPLEMENT_REFLECTABLE_TYPE(ezInt8);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezUInt8);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezInt16);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezUInt16);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezInt32);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezUInt32);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezInt64);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezUInt64);

EZ_IMPLEMENT_REFLECTABLE_TYPE(ezConstCharPtr)

EZ_IMPLEMENT_REFLECTABLE_TYPE(ezVec2);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezVec3);
EZ_IMPLEMENT_REFLECTABLE_TYPE(ezVec4);