#include <JoltPlugin/JoltPluginPCH.h>

EZ_STATICLINK_LIBRARY(JoltPlugin)
{
  if (bReturn)
    return;

  EZ_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltActorComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltDynamicActorComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltQueryShapeActorComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltStaticActorComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltTriggerComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltCharacterControllerComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltDefaultCharacterComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltBreakableSlabComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltClothSheetComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltHitboxComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRagdollComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRopeComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltSettingsComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltVisColMeshComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_Jolt6DOFConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConeConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltDistanceConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltFixedConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltGrabObjectComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltHingeConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltPointConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSliderConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSwingTwistConstraintComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltMeshResource);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeBoxComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCapsuleComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeConvexHullComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCylinderComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeSphereComponent);
  EZ_STATICLINK_REFERENCE(JoltPlugin_Startup);
  EZ_STATICLINK_REFERENCE(JoltPlugin_System_JoltContacts);
  EZ_STATICLINK_REFERENCE(JoltPlugin_System_JoltCore);
  EZ_STATICLINK_REFERENCE(JoltPlugin_System_JoltWorldModule);
}
