..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\Core
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\Foundation
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\GameEngine
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\RendererCore
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\RendererFoundation
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\RendererVulkan
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\RendererDX11
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\Texture
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\Engine\Utilities
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\AiPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\FileServePlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\FmodPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\GameComponentsPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\InspectorPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\JoltPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\KrautPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\OpenXRPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\ParticlePlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\ProcGenPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\RecastPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\RenderDocPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\RmlUiPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\AngelScriptPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\EnginePlugins\VisualScriptPlugin
..\Output\Bin\WinVs2022Debug64\ezStaticLinkUtil.exe ..\Code\UnitTests\TestFramework
