..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\Foundation
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\Core
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\Texture
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\GameEngine
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\RendererFoundation
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\RendererCore
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\System
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\TestFramework
..\Output\Bin\WinVs2017Debug64\StaticLinkUtil.exe C:\ezEngine\Trunk\Code\Engine\Utilities