#include <Foundation/FoundationPCH.h>

EZ_STATICLINK_LIBRARY(Foundation)
{
  if (bReturn)
    return;

  EZ_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_FileSystemConfig);
  EZ_STATICLINK_REFERENCE(Foundation_Application_Config_Implementation_PluginConfig);
  EZ_STATICLINK_REFERENCE(Foundation_CodeUtils_Expression_Implementation_ExpressionByteCode);
  EZ_STATICLINK_REFERENCE(Foundation_CodeUtils_Expression_Implementation_ExpressionDeclarations);
  EZ_STATICLINK_REFERENCE(Foundation_Communication_Implementation_Message);
  EZ_STATICLINK_REFERENCE(Foundation_Communication_Implementation_MessageLoop);
  EZ_STATICLINK_REFERENCE(Foundation_Communication_Implementation_RemoteMessage);
  EZ_STATICLINK_REFERENCE(Foundation_Configuration_Implementation_CVar);
  EZ_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_DefaultImplementations_Implementation_ZeroInitializer);
  EZ_STATICLINK_REFERENCE(Foundation_DataProcessing_Stream_Implementation_ProcessingStreamProcessor);
  EZ_STATICLINK_REFERENCE(Foundation_IO_Archive_Implementation_DataDirTypeArchive);
  EZ_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_DataDirTypeFolder);
  EZ_STATICLINK_REFERENCE(Foundation_IO_FileSystem_Implementation_FileSystem);
  EZ_STATICLINK_REFERENCE(Foundation_Logging_Implementation_LogEntry);
  EZ_STATICLINK_REFERENCE(Foundation_Math_Implementation_Math);
  EZ_STATICLINK_REFERENCE(Foundation_Math_Implementation_Random);
  EZ_STATICLINK_REFERENCE(Foundation_Memory_Implementation_FrameAllocator);
  EZ_STATICLINK_REFERENCE(Foundation_Platform_Win_DirectoryWatcher_Win);
  EZ_STATICLINK_REFERENCE(Foundation_Profiling_Implementation_Profiling);
  EZ_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_AbstractProperty);
  EZ_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyAttributes);
  EZ_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_PropertyPath);
  EZ_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_RTTI);
  EZ_STATICLINK_REFERENCE(Foundation_Reflection_Implementation_StandardTypes);
  EZ_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_AbstractObjectGraph);
  EZ_STATICLINK_REFERENCE(Foundation_Serialization_Implementation_GraphVersioning);
  EZ_STATICLINK_REFERENCE(Foundation_System_Implementation_StackTracer);
  EZ_STATICLINK_REFERENCE(Foundation_Threading_Implementation_TaskSystem);
  EZ_STATICLINK_REFERENCE(Foundation_Threading_Implementation_ThreadUtils);
  EZ_STATICLINK_REFERENCE(Foundation_Time_Implementation_Clock);
  EZ_STATICLINK_REFERENCE(Foundation_Time_Implementation_Time);
  EZ_STATICLINK_REFERENCE(Foundation_Time_Implementation_Timestamp);
  EZ_STATICLINK_REFERENCE(Foundation_Types_Implementation_VarianceTypes);
  EZ_STATICLINK_REFERENCE(Foundation_Types_Implementation_VariantTypeRegistry);
}
