#pragma once

#include <Core/CoreDLL.h>
#include <Core/World/Declarations.h>
#include <Foundation/Strings/StringView.h>

/// Wraps a game object handle such that it is logged as a clickable link.
///
/// The log message will contain a link in the form '[[Display Text|ezObject:<handle>]]'. Such a link is only
/// meaningful inside the editor: when the message is forwarded from the engine process to the editor,
/// the handle is translated into the document and object GUID that the editor can navigate to.
/// In all other contexts (game runtime, log files, console) the link markup is simply part of the text.
///
/// If no display text is given, the name of the game object is used, or its handle value, if the object
/// doesn't exist anymore or has no name.
///
/// Example:
///   ezLog::Error("Object {} has an invalid setup.", ezArgGameObject(hObject));
struct ezArgGameObject
{
  inline explicit ezArgGameObject(ezGameObjectHandle hObject, ezStringView sDisplayText = {})
    : m_hObject(hObject)
    , m_sDisplayText(sDisplayText)
  {
  }

  /// Convenience overload, so that a game object pointer can be passed in directly.
  EZ_CORE_DLL explicit ezArgGameObject(const ezGameObject* pObject, ezStringView sDisplayText = {});

  ezGameObjectHandle m_hObject;
  ezStringView m_sDisplayText;
};

/// Wraps a component handle such that it is logged as a clickable link.
///
/// Works exactly like ezArgGameObject, but generates a link of the form '[[Display Text|ezComponent:<handle>]]'.
/// Clicking such a link in the editor selects the game object that owns the component.
///
/// If no display text is given, the name of the component's owner is used, prefixed with the component type name.
struct ezArgComponent
{
  inline explicit ezArgComponent(ezComponentHandle hComponent, ezStringView sDisplayText = {})
    : m_hComponent(hComponent)
    , m_sDisplayText(sDisplayText)
  {
  }

  /// Convenience overload, so that a component pointer can be passed in directly.
  EZ_CORE_DLL explicit ezArgComponent(const ezComponent* pComponent, ezStringView sDisplayText = {});

  ezComponentHandle m_hComponent;
  ezStringView m_sDisplayText;
};

EZ_CORE_DLL ezStringView BuildString(char* szTmp, ezUInt32 uiLength, const ezArgGameObject& arg);
EZ_CORE_DLL ezStringView BuildString(char* szTmp, ezUInt32 uiLength, const ezArgComponent& arg);

/// Utilities to create and parse the link targets generated by ezArgGameObject and ezArgComponent.
///
/// The editor uses these to translate a handle based link into an 'asset:<doc-guid>#<obj-guid>' link.
/// Runtime code should not need to use this directly.
struct EZ_CORE_DLL ezWorldLogLinkUtils
{
  /// The link scheme used for game object links.
  static constexpr ezStringView s_sGameObjectScheme = "ezObject:"_ezsv;

  /// The link scheme used for component links.
  static constexpr ezStringView s_sComponentScheme = "ezComponent:"_ezsv;

  /// Writes the display text and link target for a game object into out_sResult.
  ///
  /// If sDisplayText is empty, a name is derived from the object, if it can still be found in its world.
  static void AppendGameObjectLink(ezStringBuilder& out_sResult, ezGameObjectHandle hObject, ezStringView sDisplayText);

  /// Same as AppendGameObjectLink() but for components.
  static void AppendComponentLink(ezStringBuilder& out_sResult, ezComponentHandle hComponent, ezStringView sDisplayText);

  /// Extracts a game object handle from a link target that uses s_sGameObjectScheme.
  ///
  /// Returns false if the target doesn't use that scheme or is malformed.
  static bool ParseGameObjectLink(ezStringView sLinkTarget, ezGameObjectHandle& out_hObject);

  /// Same as ParseGameObjectLink() but for components.
  static bool ParseComponentLink(ezStringView sLinkTarget, ezComponentHandle& out_hComponent);
};
