set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG "Debug")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV "Dev")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE "Shipping")

set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG_UPPER "DEBUG")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV_UPPER "DEV")
set_property(GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE_UPPER "SHIPPING")

set_property(GLOBAL PROPERTY EZ_DEV_BUILD_LINKERFLAGS "DEBUG")


macro(ez_pull_config_vars)

	get_property(EZ_BUILDTYPENAME_DEBUG GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG)
	get_property(EZ_BUILDTYPENAME_DEV GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV)
	get_property(EZ_BUILDTYPENAME_RELEASE GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE)
	
	get_property(EZ_BUILDTYPENAME_DEBUG_UPPER GLOBAL PROPERTY EZ_BUILDTYPENAME_DEBUG_UPPER)
	get_property(EZ_BUILDTYPENAME_DEV_UPPER GLOBAL PROPERTY EZ_BUILDTYPENAME_DEV_UPPER)
	get_property(EZ_BUILDTYPENAME_RELEASE_UPPER GLOBAL PROPERTY EZ_BUILDTYPENAME_RELEASE_UPPER)
	
	get_property(EZ_DEV_BUILD_LINKERFLAGS GLOBAL PROPERTY EZ_DEV_BUILD_LINKERFLAGS)

endmacro()
