set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21) # API level
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_NDK "D:/android-ndk-r20")
set(CMAKE_ANDROID_STL_TYPE gnustl_static)
set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang)