#include <PCH.h>

#include <PhysXPlugin/PhysXPluginDLL.h>

EZ_STATICLINK_LIBRARY(PhysXPlugin)
{
  if (bReturn)
    return;

  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxActorComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxCenterOfMassComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxCharacterControllerComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxCharacterProxyComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxDynamicActorComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxSettingsComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Components_Implementation_PxStaticActorComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Joints_Implementation_PxDistanceJointComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Joints_Implementation_PxFixedJointComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Joints_Implementation_PxJointComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Resources_Implementation_PxMeshResource);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Shapes_Implementation_PxShapeBoxComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Shapes_Implementation_PxShapeCapsuleComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Shapes_Implementation_PxShapeComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Shapes_Implementation_PxShapeConvexComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Shapes_Implementation_PxShapeSphereComponent);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_Startup);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_WorldModule_Implementation_PhysX);
  EZ_STATICLINK_REFERENCE(PhysXPlugin_WorldModule_Implementation_PhysXWorldModule);
}
