#pragma once

#include <EditorFramework/EditorFrameworkDLL.h>
#include <Foundation/Containers/Set.h>
#include <Foundation/IO/OSFile.h>
#include <Foundation/IO/Stream.h>
#include <Foundation/Logging/Log.h>
#include <Foundation/Types/Status.h>

struct ezPathPatternFilter;
class ezAssetCurator;
class ezApplicationFileSystemConfig;
class ezPlatformProfile;
class ezProgressRange;

//////////////////////////////////////////////////////////////////////////

/// The steps around ezProjectExport::ExportProjectComplete(), all of which can be skipped.
///
/// The defaults are what the 'Export Project' dialog starts out with, ie. do everything.
struct EZ_EDITORFRAMEWORK_DLL ezProjectExportOptions
{
  /// Build the project's C++ plugin first, so that the exported binaries match the current code.
  /// Has no effect on a project without C++ code.
  bool m_bCompileCppPlugin = true;

  /// Transform all assets first. Without this, assets that were modified since the last transform are
  /// exported in their previous state, and assets never transformed for the active profile are missing
  /// from the export entirely.
  bool m_bTransformAssets = true;

  /// See ezProjectExport::ExportProject().
  bool m_bCreateLaunchScripts = true;
};

struct EZ_EDITORFRAMEWORK_DLL ezProjectExport
{
  /// Runs the full export, as triggered by the 'Export Project' dialog.
  ///
  /// Does the optional steps in ezProjectExportOptions, then ExportProject() for the currently active
  /// asset profile and the editor's data directory configuration. The target directory is *cleared*
  /// first - see ExportProject().
  ///
  /// Everything that the export logs is captured and written to 'ExportLog.txt' in the target directory,
  /// and returned through out_pLog when that is not null. That means it does not show up in the editor's
  /// log window, so the returned status is the only indication of failure a caller gets without reading
  /// the log.
  static ezStatus ExportProjectComplete(ezStringView sTargetDirectory, const ezProjectExportOptions& options, ezStringBuilder* out_pLog = nullptr);


  /// Exports the project to szTargetDirectory.
  ///
  /// If bCreateLaunchScripts is true, .bat files for launching the exported project are written to the target
  /// directory. If the project has a custom game executable (see FindCustomGameExecutable()), a single script for
  /// that executable is created, otherwise one script per exported scene, which launches the scene in ezPlayer.
  static ezResult ExportProject(const char* szTargetDirectory, const ezPlatformProfile* pPlatformProfile, const ezApplicationFileSystemConfig& dataDirs, bool bCreateLaunchScripts = true);

  /// Returns the file name of the project's own game executable, or an empty string if there is none.
  ///
  /// The executable is the one generated by the C++ project generation, ie. it is named after the plugin name
  /// in ':project/Editor/CppProject.ddl'. An empty string is returned when the project has no C++ code, or when
  /// the executable hasn't been built yet.
  static ezString FindCustomGameExecutable();

private:
  struct DataDirectory
  {
    ezString m_sTargetDirPath;
    ezString m_sTargetDirRootName;
    ezSet<ezString> m_Files;
  };

  using DirectoryMapping = ezMap<ezString, DataDirectory>;

  static ezResult ClearTargetFolder(const char* szAbsFolderPath);
  static ezResult ScanFolder(ezSet<ezString>& out_Files, const char* szFolder, const ezPathPatternFilter& filter, ezAssetCurator* pCurator, ezDynamicArray<ezString>* pSceneFiles, const ezPlatformProfile* pPlatformProfile);
  static ezResult CopyFiles(const char* szSrcFolder, const char* szDstFolder, const ezSet<ezString>& files, ezProgressRange* pProgressRange);
  static ezResult GatherGeneratedAssetManagerFiles(ezSet<ezString>& out_Files);
  static ezResult CreateExportFilterFile(const char* szExpectedFile, const char* szFallbackFile);
  static ezResult ReadExportFilters(ezPathPatternFilter& out_DataFilter, ezPathPatternFilter& out_BinariesFilter, const ezPlatformProfile* pPlatformProfile);
  static ezResult CreateDataDirectoryDDL(const DirectoryMapping& mapping, const char* szTargetDirectory);
  static ezResult GatherAssetLookupTableFiles(DirectoryMapping& mapping, const ezApplicationFileSystemConfig& dirConfig, const ezPlatformProfile* pPlatformProfile);
  static ezResult ScanDataDirectories(DirectoryMapping& mapping, const ezApplicationFileSystemConfig& dirConfig, const ezPathPatternFilter& dataFilter, ezDynamicArray<ezString>* pSceneFiles, const ezPlatformProfile* pPlatformProfile);
  static ezResult CopyAllFiles(DirectoryMapping& mapping, const char* szTargetDirectory);
  static ezResult GatherBinaries(DirectoryMapping& mapping, const ezPathPatternFilter& filter);
  static ezResult CreateLaunchConfig(const ezDynamicArray<ezString>& sceneFiles, const char* szTargetDirectory, ezStringView sCustomGameExecutable);
  static ezResult GatherGeneratedAssetFiles(ezSet<ezString>& out_Files, const char* szProjectDirectory);
  static void AddPackageDependenciesToFileList(DirectoryMapping& ref_fileList);
};
