
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")

        set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_NAME "Linux")
		set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_PREFIX "Linux")
		set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_POSTFIX "Linux")
		set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_LINUX ON)
		set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_POSIX ON)

endif()
