
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")

    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_NAME "OSX")
    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_PREFIX "Osx")
    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_POSTFIX "OSX")

endif()