
if(EMSCRIPTEN)

    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_NAME "Web")
    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_PREFIX "Web")
    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_POSTFIX "Web")

endif()
