
if(CMAKE_SYSTEM_NAME STREQUAL "Windows") # Desktop Windows

    message(STATUS "Platform is Windows (EZ_CMAKE_PLATFORM_WINDOWS, EZ_CMAKE_PLATFORM_WINDOWS_DESKTOP)")
    message(STATUS "CMAKE_SYSTEM_VERSION is ${CMAKE_SYSTEM_VERSION}")
    message(STATUS "CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION is ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}")

    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_WINDOWS ON)
    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_WINDOWS_DESKTOP ON)

    set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_PREFIX "Win")

    if(${CMAKE_SYSTEM_VERSION} EQUAL 6.1)
        set_property(GLOBAL PROPERTY EZ_CMAKE_PLATFORM_WINDOWS_7 ON)
    endif()

endif()