#pragma once

/// \file

#include "StaticRTTI.h"
#include <Foundation/Math/Vec2.h>
#include <Foundation/Math/Vec3.h>
#include <Foundation/Math/Vec4.h>

// *********************************************
// ***** Standard POD Types for Properties *****

EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, bool);

EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, float);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, double);

EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezInt8);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezUInt8);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezInt16);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezUInt16);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezInt32);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezUInt32);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezInt64);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezUInt64);

// macros won't work with 'const char*'
typedef const char* ezConstCharPtr;
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezConstCharPtr);

EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezVec2);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezVec3);
EZ_DECLARE_REFLECTABLE_TYPE(EZ_NO_LINKAGE, ezVec4);