# Variable 'task.MSBuild.status' was defined in the Variables tab
trigger:
  branches:
    include:
    - dev
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: Job_2
  displayName: StartVM
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: none
  - task: AzureKeyVault@1
    displayName: 'Azure Key Vault: ezKeys'
    inputs:
      ConnectedServiceName: a416236e-0672-4024-bca3-853beb235e5e
      KeyVaultName: ezKeys
      SecretsFilter: AzureFunctionKey
  - task: PowerShell@2
    displayName: StartVM
    continueOnError: true
    inputs:
      targetType: inline
      script: Invoke-RestMethod -Uri "https://ezengineci.azurewebsites.net/api/StartVM?code=$(AzureFunctionKey)&vmname=Windows10-1809"
- job: Job_1
  displayName: Android-x86
  timeoutInMinutes: 180
  pool:
    name: Default
    demands:
    - Agent.OS -equals Windows_NT
  steps:
  - checkout: self
    submodules: true
    lfs: true
    clean: false
  - task: AzureKeyVault@1
    displayName: 'Azure Key Vault: ezKeys'
    inputs:
      ConnectedServiceName: a416236e-0672-4024-bca3-853beb235e5e
      KeyVaultName: ezKeys
      SecretsFilter: AzureBlobPW
  - task: CMake@1
    displayName: CMake x64
    enabled: False
    inputs:
      cwd: build\x64
      cmakeArgs: -DCMAKE_PREFIX_PATH=$(System.DefaultWorkingDirectory)\ThirdPartyUWPx86\vs141x64 -DEZ_QT_DIR="$(System.DefaultWorkingDirectory)\ThirdPartyUWPx86\vs141x64" -DEZ_BUILD_PHYSX=0 -DEZ_BUILD_FMOD=0 -DEZ_BUILD_GAMES=0 -DEZ_COMPILE_ENGINE_AS_DLL=1 -DEZ_ENABLE_QT_SUPPORT=1 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=10.0.18362.0 -G "Visual Studio 16 2019 Win64" ../../
  - task: CMake@1
    displayName: CMake build RemoteTestHarness
    enabled: False
    inputs:
      cwd: build\x64
      cmakeArgs: --build . --target RemoteTestHarness --config Debug
  - task: CMake@1
    displayName: CMake Android Ninja
    inputs:
      cwd: build\Android-x86-Dev
      cmakeArgs: -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="$(System.DefaultWorkingDirectory)\install\Android-x86-Dev"  -DCMAKE_TOOLCHAIN_FILE="$(ANDROID_NDK_HOME)\build\cmake\android.toolchain.cmake"  -DANDROID_ABI="x86"  -DANDROID_PLATFORM="23"  -DEZ_ENABLE_QT_SUPPORT="0"  -DEZ_BUILD_SAMPLES="0"  -DCMAKE_BUILD_TYPE="Dev" -DCMAKE_MAKE_PROGRAM="C:\Program Files\CMake\bin\ninja.exe" ../../
  - task: CmdLine@2
    displayName: Build
    inputs:
      script: >-
        cd $(System.DefaultWorkingDirectory)\build\Android-x86-Dev

        ninja libFoundationTest.so
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
      filePath: Write-Host "##vso[task.setvariable variable=task.MSBuild.status]success"
      script: Write-Host "##vso[task.setvariable variable=task.MSBuild.status]success"
  - task: CmdLine@2
    displayName: List files
    condition: always()
    inputs:
      script: >
        dir /s /o $(System.DefaultWorkingDirectory)\Output
...
