# Variable 'unityfiles' was defined in the Variables tab
trigger:
  branches:
    include:
    - dev
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: StartVM
  displayName: StartVM
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: none
  - task: AzureKeyVault@1
    displayName: 'Azure Key Vault: ezKeys'
    inputs:
      ConnectedServiceName: a416236e-0672-4024-bca3-853beb235e5e
      KeyVaultName: ezKeys
      SecretsFilter: AzureFunctionKey
  - task: PowerShell@2
    displayName: StartVM
    continueOnError: true
    inputs:
      targetType: inline
      script: Invoke-RestMethod -Uri "https://ezengineci.azurewebsites.net/api/StartVM?code=$(AzureFunctionKey)&vmname=Ubuntu-22.04"
- job: Job_1
  displayName: Linux-x64
  pool:
    name: Default
    demands:
    - Agent.OS -equals Linux
  steps:
  - checkout: self
    submodules: true
    lfs: true
  - task: Bash@3
    displayName: Apt-Get
    inputs:
      targetType: inline
      script: |
        sudo apt-get update
        sudo apt-get install -y cmake uuid-dev gcc-12 g++-12 libx11-dev build-essential qt6-base-dev libqt6svg6-dev qt6-base-private-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev xvfb lightdm libtinfo5 vulkan-tools
        # sudo add-apt-repository ppa:kisak/kisak-mesa -y 
        # sudo apt-get install -y mesa-vulkan-drivers libgl1-mesa-dev
  - task: Bash@3
    displayName: Info
    inputs:
      targetType: inline
      script: >-
        lscpu | grep -E '^Thread|^Core|^Socket|^CPU\('

        git config --list

        dpkg --list | grep compiler
  - task: CMake@1
    displayName: CMake
    inputs:
      cmakeArgs: -DCMAKE_BUILD_TYPE=Dev -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12 -DEZ_ENABLE_FOLDER_UNITY_FILES=$(unityfiles) -DEZ_BUILD_EXPERIMENTAL_VULKAN=ON -DEZ_EXPERIMENTAL_EDITOR_ON_LINUX=ON -G "Unix Makefiles" ../
  - task: Bash@3
    displayName: Make
    inputs:
      targetType: inline
      script: make -C ./build -j$(nproc)
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
      script: Write-Host "##vso[task.setvariable variable=task.MSBuild.status]success"
  - task: Bash@3
    displayName: FoundationTest
    condition: eq(variables['task.MSBuild.status'], 'success')
    inputs:
      targetType: inline
      script: ./Output/Bin/LinuxMakeGccDev64/FoundationTest -nosave -nogui -all -outputDir $(Build.ArtifactStagingDirectory)/FoundationTest
  - task: Bash@3
    displayName: CoreTest
    condition: eq(variables['task.MSBuild.status'], 'success')
    inputs:
      targetType: inline
      script: |
        killall Xvfb
        sleep 1
        export DISPLAY=:1
        Xvfb :1 -screen 0 1024x768x16 &
        sleep 1
        exec lightdm-session &
        sleep 2
        ./Output/Bin/LinuxMakeGccDev64/CoreTest -nosave -nogui -all -outputDir $(Build.ArtifactStagingDirectory)/CoreTest
  - task: Bash@3
    displayName: ToolsFoundationTest
    condition: eq(variables['task.MSBuild.status'], 'success')
    inputs:
      targetType: inline
      script: ./Output/Bin/LinuxMakeGccDev64/ToolsFoundationTest -nosave -nogui -all -outputDir $(Build.ArtifactStagingDirectory)/ToolsFoundationTest
  - task: Bash@3
    displayName: RendererTest
    condition: eq(variables['task.MSBuild.status'], 'success')
    inputs:
      targetType: inline
      script: |
        export DISPLAY=:1
        export VK_ICD_FILENAMES=/usr/local/share/vulkan/icd.d/lvp_icd.x86_64.json
        vulkaninfo --summary
        ./Output/Bin/LinuxMakeGccDev64/RendererTest -nosave -nogui -all -outputDir $(Build.ArtifactStagingDirectory)/RendererTest
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
...
